### ISSUE TITLE
Unable to access the demo web UI on the LAN

### ISSUE THREAD

**Issue by rango886** [facebookresearch/sam2#366]
After deploying an application with Docker, I can access it on the host machine using 127.0.0.1:7262. However, when I try to access it from other devices on the local network using  192.168.x.x  IP address, I get a "Uh oh, this browser isn’t supported." error.

![iCKqpQI35i](https://github.com/user-attachments/assets/823e7370-5b4e-4fac-bb04-7d98bb296945)

**Comment by ronghanghu** [comment]
Hi @rango886, to access it from another machine, you'll also need to set the backend API address, which is specified as the `API_URL` env in this line https://github.com/facebookresearch/sam2/blob/c98aa6bea377d5c000cdc80197ce402dbf5304dc/demo/backend/server/app_conf.py#L14 and set to a local address `http://localhost:7263` in `docker-compose.yaml` in https://github.com/facebookresearch/sam2/blob/c98aa6bea377d5c000cdc80197ce402dbf5304dc/docker-compose.yaml#L26

You can change it to `http://192.168.x.x:7263` (i.e. the server machine's IP address running the backend). Hope this resolves your issue

**Comment by rango886** [comment]
> Hi @rango886, to access it from another machine, you'll also need to set the backend API address, which is specified as the `API_URL` env in this line
> 
> https://github.com/facebookresearch/sam2/blob/c98aa6bea377d5c000cdc80197ce402dbf5304dc/demo/backend/server/app_conf.py#L14
> 
> and set to a local address `http://localhost:7263` in `docker-compose.yaml` in
> https://github.com/facebookresearch/sam2/blob/c98aa6bea377d5c000cdc80197ce402dbf5304dc/docker-compose.yaml#L26
> 
> You can change it to `http://192.168.x.x:7263` (i.e. the server machine's IP address running the backend), so that it can be accessed from other hosts. Hope this resolves your issue

It seems that it doesn't work. After modifying the environment variable.
![uvLJBeH7nB](https://github.com/user-attachments/assets/fbd30ed6-4d00-42f7-b100-f79e36e8503f)
I found that it is displayed that the browser does not support video features. 
![d0X69Tvny6](https://github.com/user-attachments/assets/8c1ffa27-b088-4eb9-96e2-21fd1b92ef10)
I am using the latest version of Chrome. I found on the Internet that the front end may use this browser API https://developer.mozilla.org/en-US/docs/Web/API/VideoEncoder . For this API, local access does not use https, while within the local area network, https is required for use.

**Comment by MIKE-GUO233** [comment]
Please modify Chrome settings to enable the VideoEncoder feature when accessing over HTTP.

1. Open `chrome://flags/` in your chrome.
2. Add your IP address to the **Insecure origins treated as secure** setting and relaunch the browser.

<img width="500" alt="image" src="https://github.com/user-attachments/assets/8c42ce7b-50b6-43e3-b7e9-4da94996a124">

**Comment by rango886** [comment]
> Please modify Chrome settings to enable the VideoEncoder feature when accessing over HTTP.
> 
> 1. Open `chrome://flags/` in your chrome.
> 2. Add your IP address to the **Insecure origins treated as secure** setting and relaunch the browser.
> 
> <img alt="image" width="500" src="https://private-user-images.githubusercontent.com/60096490/375296874-8c42ce7b-50b6-43e3-b7e9-4da94996a124.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NTAzODYsIm5iZiI6MTcyODU1MDA4NiwicGF0aCI6Ii82MDA5NjQ5MC8zNzUyOTY4NzQtOGM0MmNlN2ItNTBiNi00M2UzLWI3ZTktNGRhOTQ5OTZhMTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDA4NDgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2NGEwY2ZkYWFmYjhkODM5MDZiMzk0NjMyNzgyZjBlYWQzYmYzNjA3ZjMzZTAyNzM1YTU4ZmQwM2ZkOTA1OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Lbcg-6oJIA1hImcQs9ze3copmkNSy-acoUYYoVVXTt0">

![NrH8EWivDk](https://github.com/user-attachments/assets/3a704619-c557-4891-bb76-466072b842de)

Thank you. It can be used in the local area network now. However, it is also necessary to click this button and set the IP address of the local area network to be able to use it.

**Comment by crashr** [comment]
> Hi @rango886, to access it from another machine, you'll also need to set the backend API address, which is specified as the `API_URL` env in this line
> 
> https://github.com/facebookresearch/sam2/blob/c98aa6bea377d5c000cdc80197ce402dbf5304dc/demo/backend/server/app_conf.py#L14
> 
> and set to a local address `http://localhost:7263` in `docker-compose.yaml` in
> https://github.com/facebookresearch/sam2/blob/c98aa6bea377d5c000cdc80197ce402dbf5304dc/docker-compose.yaml#L26
> 
> You can change it to `http://192.168.x.x:7263` (i.e. the server machine's IP address running the backend), so that it can be accessed from other hosts. Hope this resolves your issue

Didn't work for me. In the console I still see requests to http://localhost:7263
I worked around it with 

`socat TCP-LISTEN:7263,reuseaddr,fork TCP:192.168.178.56:7263`

**Comment by raedle** [comment]
There are currently different places for changing the server endpoint:

**Frontend**

https://github.com/facebookresearch/sam2/blob/c98aa6bea377d5c000cdc80197ce402dbf5304dc/demo/frontend/src/demo/DemoConfig.tsx#L34-L35

The endpoint is also stored in local storage, which has precedence over the value in the `DemoConfig.tsx`. Just in case, make sure to delete the local storage key before opening the site (or use the browser's incognito mode) or change the endpoint via the settings modal shared above:

```
localStorage.removeItem('SAM2_SETTINGS_KEY')
```

**Backend**

https://github.com/facebookresearch/sam2/blob/c98aa6bea377d5c000cdc80197ce402dbf5304dc/docker-compose.yaml#L26

Note: there might be CORS restrictions if the page isn't loaded from localhost

**Comment by songhat** [comment]
![image](https://github.com/user-attachments/assets/9adc4d1e-4b60-4965-ae2f-cec56b97aa0b)
I deployed it on a local server (not via docker), and the browser on the server can access it, but my local browser cannot access it.

**Comment by aiicore** [comment]
btw. The error `This demo is not optimized for your device ...` also appears when directory `/data/gallery`  at the backend side is empty.

Backend log:
```
GraphQL request:2:3
1 | query DemoPageQuery {
2 |   defaultVideo {
  |   ^
3 |     path
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/graphql/execution/execute.py", line 523, in execute_field
    result = resolve_fn(source, info, **args)
  File "/opt/conda/lib/python3.10/site-packages/strawberry/schema/schema_converter.py", line 739, in _resolver
    return _get_result_with_extensions(
  File "/opt/conda/lib/python3.10/site-packages/strawberry/schema/schema_converter.py", line 726, in extension_resolver
    return reduce(
  File "/opt/conda/lib/python3.10/site-packages/strawberry/schema/schema_converter.py", line 721, in wrapped_get_result
    return _get_result(
  File "/opt/conda/lib/python3.10/site-packages/strawberry/schema/schema_converter.py", line 678, in _get_result
    return field.get_result(
  File "/opt/conda/lib/python3.10/site-packages/strawberry/types/field.py", line 224, in get_result
    return self.base_resolver(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/strawberry/types/fields/resolver.py", line 211, in __call__
    return self.wrapped_func(*args, **kwargs)
  File "/opt/sam2/server/data/schema.py", line 78, in default_video
    return next(iter(all_videos.values()))
StopIteration
```

**Comment by lzh82058** [comment]
Hi @songhat,I met the same problem,"This demo is not optimized for your device. Please try again on a different device with a larger screen." have you solved it?

**Comment by Dam445** [comment]
> ![image](https://private-user-images.githubusercontent.com/48643755/377953135-9adc4d1e-4b60-4965-ae2f-cec56b97aa0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMTQxMTQsIm5iZiI6MTczMjAxMzgxNCwicGF0aCI6Ii80ODY0Mzc1NS8zNzc5NTMxMzUtOWFkYzRkMWUtNGI2MC00OTY1LWFlMmYtY2VjNTZiOTdhYTBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDEwNTY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1OTk2YzhhNGE2NGZiNzRiZGEzMzgyYzcyMjBkY2RmMzY3YjNkZGQyMmE2YzI2YmFlOTFlODVkMzJjNzQ0YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KkAtB27LE2SLNmUe--62CpwKJv5kK0nYfV3f172WPs4) I deployed it on a local server (not via docker), and the browser on the server can access it, but my local browser cannot access it.



> Hi @songhat,I met the same problem,"This demo is not optimized for your device. Please try again on a different device with a larger screen." have you solved it?

@songhat @lzh82058 . Same problem. 
Solution : Change code of 'SAM2DemoApp.tsx' file.
Path: 'demo/frontend/src/demo/SAM2DemoApp.tsx'
```python
import '@/assets/scss/App.scss';
import ErrorReport from '@/common/error/ErrorReport';
import RelayEnvironmentProvider from '@/graphql/RelayEnvironmentProvider';
import RootLayout from '@/layouts/RootLayout';
import SAM2DemoPage from '@/routes/DemoPageWrapper';
import PageNotFoundPage from '@/routes/PageNotFoundPage';
import useSettingsContext from '@/settings/useSettingsContext';
import {Route, Routes} from 'react-router-dom';

export default function DemoAppWrapper() {
  const {settings} = useSettingsContext();
  return (
    <RelayEnvironmentProvider
      endpoint={settings.videoAPIEndpoint}>
      <DemoApp />
    </RelayEnvironmentProvider>
  );
}

function DemoApp() {
  return (
    <>
      <Routes>
        <Route element={<RootLayout />}>
          <Route index={true} element={<SAM2DemoPage />} />
          <Route path="*" element={<PageNotFoundPage />} />
        </Route>
      </Routes>
      <ErrorReport />
    </>
  );
}
```

**Comment by songhat** [comment]
> > ![image](https://private-user-images.githubusercontent.com/48643755/377953135-9adc4d1e-4b60-4965-ae2f-cec56b97aa0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMTQxMTQsIm5iZiI6MTczMjAxMzgxNCwicGF0aCI6Ii80ODY0Mzc1NS8zNzc5NTMxMzUtOWFkYzRkMWUtNGI2MC00OTY1LWFlMmYtY2VjNTZiOTdhYTBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDEwNTY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1OTk2YzhhNGE2NGZiNzRiZGEzMzgyYzcyMjBkY2RmMzY3YjNkZGQyMmE2YzI2YmFlOTFlODVkMzJjNzQ0YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KkAtB27LE2SLNmUe--62CpwKJv5kK0nYfV3f172WPs4) I deployed it on a local server (not via docker), and the browser on the server can access it, but my local browser cannot access it.
> 
> > Hi @songhat,I met the same problem,"This demo is not optimized for your device. Please try again on a different device with a larger screen." have you solved it?
> 
> @songhat @lzh82058 . Same problem. Solution : Change code of 'SAM2DemoApp.tsx' file. Path: 'demo/frontend/src/demo/SAM2DemoApp.tsx'
> 
> ```python
> import '@/assets/scss/App.scss';
> import ErrorReport from '@/common/error/ErrorReport';
> import RelayEnvironmentProvider from '@/graphql/RelayEnvironmentProvider';
> import RootLayout from '@/layouts/RootLayout';
> import SAM2DemoPage from '@/routes/DemoPageWrapper';
> import PageNotFoundPage from '@/routes/PageNotFoundPage';
> import useSettingsContext from '@/settings/useSettingsContext';
> import {Route, Routes} from 'react-router-dom';
> 
> export default function DemoAppWrapper() {
>   const {settings} = useSettingsContext();
>   return (
>     <RelayEnvironmentProvider
>       endpoint={settings.videoAPIEndpoint}>
>       <DemoApp />
>     </RelayEnvironmentProvider>
>   );
> }
> 
> function DemoApp() {
>   return (
>     <>
>       <Routes>
>         <Route element={<RootLayout />}>
>           <Route index={true} element={<SAM2DemoPage />} />
>           <Route path="*" element={<PageNotFoundPage />} />
>         </Route>
>       </Routes>
>       <ErrorReport />
>     </>
>   );
> }
> ```

You use your computer and turn your browser to full screen

**Comment by Dam445** [comment]
@songhat I use a laptop with Chrome in normal mode in full screen (no with F11).

**Comment by songhat** [comment]
> @songhat I use a laptop with Chrome in normal mode in full screen (no with F11).

you can check your console log in f12. see what wrong is going.

**Comment by Dam445** [comment]
> > @songhat I use a laptop with Chrome in normal mode in full screen (no with F11).
> 
> you can check your console log in f12. see what wrong is going.

I understood the reason. The initial code worked fine. The issue was due to the incorrect configuration of the backend on Windows at the start.
When launching the frontend, I encountered this error: Well, this is embarrassing... This demo is not optimized for your device. Please try again on a different device with a larger screen.

After modifying the 'SAM2DemoApp.tsx' file to remove this error, I found the actual issue.
![image](https://github.com/user-attachments/assets/a73cb437-0a66-4253-959f-c98e9922a749)

However, when connecting the backend and then the frontend in this order without any file modifications, there was no problem at all. In summary, it was due to having that screen width error first that I initially thought the source of my problem was the screen width of my laptop, while it was just a backend configuration issue and the screen width had nothing to do with it.

**Comment by RemyNtshaykolo** [comment]
> Please modify Chrome settings to enable the VideoEncoder feature when accessing over HTTP.
> 
> 1. Open `chrome://flags/` in your chrome.
> 2. Add your IP address to the **Insecure origins treated as secure** setting and relaunch the browser.
> 
> <img alt="image" width="500" src="https://private-user-images.githubusercontent.com/60096490/375296874-8c42ce7b-50b6-43e3-b7e9-4da94996a124.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc5MDcxNzYsIm5iZiI6MTczNzkwNjg3NiwicGF0aCI6Ii82MDA5NjQ5MC8zNzUyOTY4NzQtOGM0MmNlN2ItNTBiNi00M2UzLWI3ZTktNGRhOTQ5OTZhMTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTI2VDE1NTQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwMDEwMWNjY2Q4NzgzMmIwZWMzYmNhOWFkMTc4YWEyODc2MGE3YTc1YzAxNTFiMmIyMDg1ODI5YzUyMTA2NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XrBm7-X9DfbiDZr_pjvgqtMsNOl3XAdjNBNkfFi-Jrw">

And don't forget to select Enabled on the right

**Comment by stardust123456** [comment]
> > 你好[@rango886](https://github.com/rango886)`API_URL`，要从另一台机器访问它，你还需要设置后端 API 地址，该地址在此行中指定为env
> > 
> >   
> >     
> >       [sam2/demo/后端/服务器/app_conf.py](https://github.com/facebookresearch/sam2/blob/c98aa6bea377d5c000cdc80197ce402dbf5304dc/demo/backend/server/app_conf.py#L14)
> >     
> >     
> >          第 14 行
> >       [c98aa6b](/facebookresearch/sam2/commit/c98aa6bea377d5c000cdc80197ce402dbf5304dc)
> >     
> >   
> >   
> >     
> > 
> >         
> >           
> >            API_URL  =  os.getenv ( " API_URL"，"http://localhost:7263 " )
> >         
> >     
> >   
> > 
> > 
> > 并设置为`http://localhost:7263`本地地址`docker-compose.yaml`
> > 
> >   
> >     
> >       [sam2/docker-compose.yaml](https://github.com/facebookresearch/sam2/blob/c98aa6bea377d5c000cdc80197ce402dbf5304dc/docker-compose.yaml#L26)
> >     
> >     
> >          第 26 行
> >       [c98aa6b](/facebookresearch/sam2/commit/c98aa6bea377d5c000cdc80197ce402dbf5304dc)
> >     
> >   
> >   
> >     
> > 
> >         
> >           
> >           -API_URL =http://本地主机:7263 
> >         
> >     
> >   
> > 
> > 
> > 您可以将其更改为`http://192.168.x.x:7263`（即运行后端的服务器计算机的 IP 地址），以便可以从其他主机访问它。希望这能解决您的问题
> 
> 对我来说没用。在控制台中我仍然看到对http://localhost:7263的请求 ，我解决了这个问题
> 
> `socat TCP-LISTEN:7263,reuseaddr,fork TCP:192.168.178.56:7263`

您好，请问您解决了或者问题吗，我也是在控制台看到对http://localhost:7263的请求，在配置文件中将localhost都改为了服务器地址，但是还是有这种显示问题

**Comment by stardust123456** [comment]
> > > [@songhat](https://github.com/songhat)我使用笔记本电脑，其中 Chrome 处于全屏正常模式（不使用 F11）。
> > 
> > 
> > 您可以通过 f12 检查您的控制台日志。看看出了什么问题。
> 
> 我明白原因了。初始代码运行良好。问题是由于开始时 Windows 上的后端配置不正确。 启动前端时，我遇到了此错误：好吧，这很尴尬……此演示未针对您的设备进行优化。请在其他屏幕更大的设备上重试。
> 
> 修改“SAM2DemoApp.tsx”文件以消除此错误后，我发现了实际问题。 ![image](https://github.com/user-attachments/assets/a73cb437-0a66-4253-959f-c98e9922a749)
> 
> 但是，正确连接后端后再连接前端，无需修改任何文件，就完全没有问题了。总结一下，就是因为先出现那个屏幕宽度错误，我一开始以为问题的根源是笔记本的屏幕宽度，结果发现只是后端配置问题，跟屏幕宽度没关系。

请问是后端配置哪里的有问题呢

**Comment by crashr** [comment]
@stardust123456 I can't help you. I don't understand Chinese.

**Comment by sarthak247** [comment]
@Dam445 How'd you manage to solve that one? Any insights?

**Comment by crashr** [comment]
@sarthak247 I ended up using this. https://huggingface.co/spaces/fffiloni/SAM2-Video-Predictor/tree/main

**Comment by Inter3D-ui** [comment]
> Hi [@rango886](https://github.com/rango886), to access it from another machine, you'll also need to set the backend API address, which is specified as the `API_URL` env in this line
> 
> [sam2/demo/backend/server/app_conf.py](https://github.com/facebookresearch/sam2/blob/c98aa6bea377d5c000cdc80197ce402dbf5304dc/demo/backend/server/app_conf.py#L14)
> 
> Line 14 in [c98aa6b](/facebookresearch/sam2/commit/c98aa6bea377d5c000cdc80197ce402dbf5304dc)
> 
>  API_URL = os.getenv("API_URL", "http://localhost:7263") 
> and set to a local address `http://localhost:7263` in `docker-compose.yaml` in
> [sam2/docker-compose.yaml](https://github.com/facebookresearch/sam2/blob/c98aa6bea377d5c000cdc80197ce402dbf5304dc/docker-compose.yaml#L26)
> 
> Line 26 in [c98aa6b](/facebookresearch/sam2/commit/c98aa6bea377d5c000cdc80197ce402dbf5304dc)
> 
>  - API_URL=http://localhost:7263 
> You can change it to `http://192.168.x.x:7263` (i.e. the server machine's IP address running the backend), so that it can be accessed from other hosts. Hope this resolves your issue

I run "yarn dev --port 7262 --host" on the server. When accessing locally, the phrase "This demo is not optimized for your device. Please try again on a different device with a larger." appeared "screen." May I ask how to solve this problem
